### ISSUE TITLE
No method: self._transform_label

### ISSUE THREAD

**Issue by muyuuuu** [Harry24k/catastrophic-overfitting#2]
What an outstanding idea in this paper. But I found some error in your code:

CustomFFGSM object has no attribute '_transform_lable', in defenses/trainers/co_adv_trainer.py.

https://github.com/Harry24k/catastrophic-overfitting/blob/22e7bbfdfc45427834779d3dcc2e96b2da10ef12/defenses/trainers/co_adv_trainer.py#L142

I didn't find this method in your torchattacks :https://github.com/Harry24k/adversarial-attacks-pytorch/blob/master/torchattacks/attack.py

how to fix it up?

**Comment by muyuuuu** [comment]
I have reimplemented it in my own repo: https://github.com/muyuuuu/Paper-ReImplement/tree/main/CO-AAAI-2021

If anyone wants to implement the algorithm can refer to it, the contribution comes from Harry24K not me, I am just carrying it, thanks to the author for his contribution.

**Comment by Harry24k** [comment]
Sorry for the late answer.
This error is caused by the version of torchattacks.
Please install torchattacks==2.12 instead of the latest version.

Anyany, [the repo](https://github.com/muyuuuu/Paper-ReImplement/tree/main/CO-AAAI-2021) is awesome :). Thank you.

**Comment by muyuuuu** [comment]
sorry to comment in closed issue, the repo url has been changed...

https://github.com/muyuuuu/Paper-ReImplement/tree/main/2021-AAAI-CO
